run-name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v7

      - name: Install dependencies
        run: |
          cd frontend && npm ci
          cd ../backend && npm ci

      - name: Format
        run: |
          cd frontend && npx prettier --write src
          cd ../backend && npx prettier --write src

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Code Formatter

      - name: Lint
        run: |
          cd frontend && npm run lint
          cd ../backend && npm run lint

      - name: Test
        run: |
          cd frontend && npm run test
          cd ../backend && npm run test

      - name: Build
        run: |
          cd frontend && npm run build
          cd ../backend && npm run build
